# Exploratory Data Analysis

## 0.0 Imports

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## 0.1 Seaborn's Grid Setup & Data Loading

In [2]:
sns.set_theme(style="whitegrid")

In [3]:
df = pd.read_csv("../data/processed/vancouver_tech_postings.csv", parse_dates=["First Posting Date"])

In [4]:
print(df.shape)

(4379, 65)

In [5]:
df.head()

,WIC Job Location Snapshot ID,Job Title,Original Job Title,NOC 2016 Code,NOC 2016 Code Name,NOC21 Code,NOC21 Code Name,External Indicator,First Posting Date,Vacancy Count,...,Condition Vision Care,Salary Condition Other Benefits,Commission PER,Commission Type,Hours Per,Hours Minimum,Hours Maximum,Work Hours,Work Hours From Time,Work Hours To Time
0,15538106.0,systems analyst,IT Systems Analyst (ESRI ArcGIS),2171.0,Information systems analysts and consultants,21222.0,Information systems specialists,1,2026-05-11,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN
1,15554305.0,business process analyst,NaN,2171.0,Information systems analysts and consultants,21221.0,Business systems specialists,0,2026-05-15,1,...,No,No,NaN,NaN,Week,40.0,40.0,Yes,09:00,17:00
2,15575608.0,information technology (IT) analyst,Government Relations Specialist,2171.0,Information systems analysts and consultants,21222.0,Information systems specialists,1,2026-05-23,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN
3,15568431.0,devops engineer,Mechatronics Engineer,2173.0,Software engineers and designers,21231.0,Software engineers and designers,1,2026-05-21,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN
4,15538267.0,software engineer,Senior Backend Engineer,2173.0,Software engineers and designers,21231.0,Software engineers and designers,1,2026-05-11,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN

## 0.2 Fixing Code Related Columns (e.g. "WIC Job Location Snapshot ID","NOC 2016 Code", "NOC21 Code")

In [6]:
code_columns = ["WIC Job Location Snapshot ID","NOC 2016 Code", "NOC21 Code"]

In [7]:
for col in code_columns:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors="coerce").astype("Int64")

In [8]:
df[code_columns].head()

   WIC Job Location Snapshot ID  NOC 2016 Code  NOC21 Code
0                      15538106           2171       21222
1                      15554305           2171       21221
2                      15575608           2171       21222
3                      15568431           2173       21231
4                      15538267           2173       21231

## 0.3 Checking  "Fist Posting Date" Data Type

In [9]:
print(df["First Posting Date"].dtypes)

datetime64[us]

In [10]:
df.head()

,WIC Job Location Snapshot ID,Job Title,Original Job Title,NOC 2016 Code,NOC 2016 Code Name,NOC21 Code,NOC21 Code Name,External Indicator,First Posting Date,Vacancy Count,...,Condition Vision Care,Salary Condition Other Benefits,Commission PER,Commission Type,Hours Per,Hours Minimum,Hours Maximum,Work Hours,Work Hours From Time,Work Hours To Time
0,15538106,systems analyst,IT Systems Analyst (ESRI ArcGIS),2171,Information systems analysts and consultants,21222,Information systems specialists,1,2026-05-11,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN
1,15554305,business process analyst,NaN,2171,Information systems analysts and consultants,21221,Business systems specialists,0,2026-05-15,1,...,No,No,NaN,NaN,Week,40.0,40.0,Yes,09:00,17:00
2,15575608,information technology (IT) analyst,Government Relations Specialist,2171,Information systems analysts and consultants,21222,Information systems specialists,1,2026-05-23,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN
3,15568431,devops engineer,Mechatronics Engineer,2173,Software engineers and designers,21231,Software engineers and designers,1,2026-05-21,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN
4,15538267,software engineer,Senior Backend Engineer,2173,Software engineers and designers,21231,Software engineers and designers,1,2026-05-11,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN

In [11]:
df.tail()

,WIC Job Location Snapshot ID,Job Title,Original Job Title,NOC 2016 Code,NOC 2016 Code Name,NOC21 Code,NOC21 Code Name,External Indicator,First Posting Date,Vacancy Count,...,Condition Vision Care,Salary Condition Other Benefits,Commission PER,Commission Type,Hours Per,Hours Minimum,Hours Maximum,Work Hours,Work Hours From Time,Work Hours To Time
4374,<NA>,software engineer,"Senior Lead Software Engineer, Network Systems",2173,Software engineers and designers,21231,Software engineers and designers,1,2024-06-19,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN
4375,<NA>,software developer,Senior Python Developer,2174,Computer programmers and interactive media dev...,21232,Software developers and programmers,1,2024-06-25,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN
4376,<NA>,software engineer,Principal Software Engineer,2173,Software engineers and designers,21231,Software engineers and designers,1,2024-06-19,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN
4377,<NA>,software developer,SAP iXp Intern - SAP Concur App Center Full St...,2174,Computer programmers and interactive media dev...,21232,Software developers and programmers,1,2024-06-19,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN
4378,<NA>,Web developer,NaN,2175,Web designers and developers,21234,Web developers and programmers,0,2024-06-21,1,...,No,No,NaN,NaN,Week,35.0,35.0,No,NaN,NaN

In [12]:
print("Period to analyze ", df["First Posting Date"].min(), "to", df["First Posting Date"].max())

Period to analyze  2024-06-01 00:00:00 to 2026-05-30 00:00:00

In [13]:
print("Rows with unparseable dates:", df["First Posting Date"].isna().sum())

Rows with unparseable dates: 0